POST http://localhost:3000/api/services
Content-Type: application/json

{
   "name": "Cuppcake",
    "description": "Um doce de pessoas, músicas mais infantis e mais calmas",
    "price": 1400,
    "image": "https://i.pinimg.com/736x/8e/bd/3f/8ebd3f88a31e16be0123eeff557064e4.jpg"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/68cacdeee1a8c773c2cf5304

###
DELETE http://localhost:3000/api/services/68cacf449f9c3a6c23125b5b

###
PUT  http://localhost:3000/api/services/68cad25f81c141f52506efaf
Content-Type: application/json

{
    "name": "Fiesta Salsa",
    "description": "Alguma descrição!",
    "price": 1754,
    "image": "https://i.pinimg.com/736x/78/3d/47/783d478fde50b0f1d23ed5db8e9e2dee.jpg"
}

###
POST  http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Festa dos Aghaters",
    "author": "Sofia",
    "description": "Festa no bar da Lora",
    "budget": 1000,
    "image": "https://i.pinimg.com/736x/59/3b/06/593b06922df153017516d0a6b4a144d3.jpg",
    "services": 
    [
        {
            "name": "Pepita",
            "description": "Hãn",
            "price": 1760,
            "image": "https://i.pinimg.com/736x/68/64/5f/68645fae490984c9943e95de11f60ffc.jpg"
        },   
        {
            "name": "Camila Loures",
            "description": "nu vai tomando",
            "price": 1800,
            "image": "https://i.pinimg.com/736x/eb/66/b6/eb66b68e45cb44fa8769313673076dba.jpg"
        }      
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/68cadc547cc70c7ec34018ec

###
DELETE http://localhost:3000/api/parties/68cadc547cc70c7ec34018ec

###
PUT http://localhost:3000/api/parties/68caddd410b1b10fd5853d7f
Content-Type: application/json

{
    "title": "Festa dos Aghaters",
    "author": "Sofia",
    "description": "Festa no bar da Lora",
    "budget": 10000,
    "image": "https://i.pinimg.com/736x/59/3b/06/593b06922df153017516d0a6b4a144d3.jpg",
    "services": 
    [
        {
            "name": "Pepita",
            "description": "Hãn",
            "price": 1760,
            "image": "https://i.pinimg.com/736x/68/64/5f/68645fae490984c9943e95de11f60ffc.jpg"
        },   
        {
            "name": "Camila Loures",
            "description": "nu vai tomando",
            "price": 1800,
            "image": "https://i.pinimg.com/736x/eb/66/b6/eb66b68e45cb44fa8769313673076dba.jpg"
        }      
    ]
}