POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço 2",
    "description": "Alguma descrição",
    "price": 1760,
    "image": "https://i.pinimg.com/1200x/29/80/31/2980313f1528619b4b8bc2f2a25f5847.jpg"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/68cacdeee1a8c773c2cf5304

###
DELETE http://localhost:3000/api/services/68cacf449f9c3a6c23125b5b
